### PR TITLE
[TAS-106] 🚸 Allow delete edition in new listing

### PR DESCRIPTION
**Pull request by nwingt**
image

### CODE REVIEW

**Comment by AuroraHuang22** [comment]
I think using the index as the key for deletion can lead to some potential issues in certain scenarios.
Maybe we can use `uuid` as `price.id`?

**Review by williamchong — APPROVED** [review]

**Comment by williamchong** [comment]
> I think using the index as the key for deletion can lead to some potential issues in certain scenarios. Maybe we can use `uuid` as `price.id`?

I think the problem would probably be with `:key="index"`

**Comment by nwingt** [comment]
Updated with UUID as key

Should we pass UUID to API too?

**Comment by williamchong** [comment]
> Updated with UUID as key
> 
> Should we pass UUID to API too?

Actually api should return uuid as id in this case, lets not add more complexity into this pr for now

**Pull request merged**
